### ISSUE TITLE
Issue with the VS Code Extension Debugging Tool: Element Values Not Refreshing Even When Parameters Are Overridden at Runtime

### ISSUE THREAD

**Issue by sajith-madhusanka** [ballerina-platform/plugin-vscode-compiler-toolkit#19] opened 2024-09-19 05:48 UTC
**Description:**
When debugging a Ballerina service using the VS Code tool, we encountered an issue where the values of local variables were not updated, even though they were modified in the source code. We were debugging a SOAP service invocation and, while debugging the `createSoap12HttpRequest` method in the `ballerina/soap` library [1], we noticed that the `req object's content-type`  header parameter did not update as expected during runtime.

Initially, the content-type is set to **"application/xml"** after setting the XML body to the req object. However, after executing the following code segment, the content-type parameter still displays as **"application/xml"** instead of the expected value:

```

} else if (body is xml) {
    req.setHeader(mime: CONTENT_TYPE, mime: TEXT_XML);
} else {
```

Refer to the below screenshot for details.

![image](https://github.com/user-attachments/assets/63432a9b-2824-4978-87b5-9170f196808c)

To further investigate, we executed the following code segment in the debugger tool's expression evaluator, which correctly showed the req object's content-type as **"text/xml"** as expected(please refer to the above screenshot).

```
req.getContentType()
```
We then used the debugger tool's expression evaluator to check the req object's entity element, which holds all parameters. We observed that the req object parameters were refreshed correctly after this step.
```
req.getEntity();
```

Refer to the below screenshot for details.

![image](https://github.com/user-attachments/assets/eb3f222e-a984-491f-ab30-a87455c948bf)

We need to verify if this is the expected behavior when debugging Ballerina internal components, such as the ballerina/soap library, or if this indicates an issue with the debugger tool that needs to be addressed.

[1] https://central.ballerina.io/ballerina/soap/1.1.0

**Steps to reproduce:**

- Deploy the attached sample Ballerina service ([sampleService.bal.txt](https://github.com/user-attachments/files/17054083/sampleService.bal.txt)). We have renamed it to sampleService.bal.txt in order to attach it to the Git issue.
- Start the VS Code debugger tool and place a breakpoint at the following line:
```
xml response = check soapClient->sendReceive(body, null);
```
- Execute the following curl command to trigger the service invocation.
 ```
curl -v  -X POST http://localhost:8080/soapService \
  -H "SOAPAction: urn:getDetails" \
  -H "Content-Type: application/xml" \
  -d '<?xml version="1.0" encoding="UTF-8"?>
  <soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope" xmlns:ser="http://example.com/service">
     <soapenv:Header/>
     <soapenv:Body>
        <ser:GetDetailsRequest/>
     </soapenv:Body>
  </soapenv:Envelope>'
```

- Use the "Step Into" option in the debugger tool until you reach the **createSoap12HttpRequest** method. Then, use the "Step Over" option to navigate through the method.

**Affected Versions:**
v4.7.6

**OS, DB, other environment details and versions:**
Mac OS

**Comment by KavinduZoysa** [comment] 2024-09-26 19:47
Closing this since the issue is moved to the ballerina vs code extension repository.

**Closed by KavinduZoysa** 2024-09-26 19:47 UTC
Labels: Type/Bug
