### ISSUE TITLE
Saving the diagrams created

### ISSUE THREAD

**Issue by franceme** [ballerina-platform/plugin-vscode-compiler-toolkit#17] opened 2023-10-09 17:54 UTC
**Description:**
As a user I would like to download or export all of the diagrams created with the IDE Plugin.
For example, download the sequence diagram to include in some PowerPoint rather than taking a small screenshot of the diagram.

**Describe your problem(s)**
n/a -> A new feature

**Describe your solution(s)**
Adding some environment flag or UI button enables a separate process to download the virtual documents as HTML files.

This **shouldn't** address creating diagrams in multiple formats.
The user should be able to print as pdf or use pandoc to convert to different formats.

**Comment by KavinduZoysa** [comment] 2024-09-26 19:46
Closing this since the issue is moved to the ballerina vs code extension repository.

**Closed by KavinduZoysa** 2024-09-26 19:46 UTC
Labels: Type/NewFeature

**Comment by franceme** [comment] 2024-10-07 03:21
> Closing this since the issue is moved to the ballerina vs code extension repository.

Can you please link to the fix?
